version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dinez
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=dinez-files-dev
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
